name: SSD-pytorch
channels:
  - pytorch
  - defaults
dependencies:
  - opencv=3.4.2
  - py-opencv=3.4.2
  - python=3.6.7
  - pytorch=1.0.0
  - torchvision=0.2.1
  - pip:
    - protobuf==3.6.1
    - pyyaml==3.13
    - tensorboardx==1.5
    - torch==1.0.0
    - tqdm==4.28.1
    - yacs==0.1.4
